# ref to https://docs.astro.build/en/guides/deploy/github/
name: Deploy Astro Site to Github Pages on Master Branch

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.VERSION }}
          package_json_file: "${{ inputs.path }}/package.json"

      - name: Install
        shell: "bash"
        working-directory: ${{ inputs.path }}
        run: pnpm install

      - name: Build
        shell: "bash"
        working-directory: ${{ inputs.path }}
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: gkzhb/gkzhb.github.io
          publish_dir: "./dist"
          keep_files: false # remove existing files
          publish_branch: main  # deploying branch
          commit_message: ${{ github.event.head_commit.message }}

